segments:
  right:
    # - function: powerline.segments.common.sys.uptime
      # priority: 50
    - function: powerline.segments.common.sys.system_load
      priority: 50
    # - function: powerline.segments.common.time.date
    # - function: powerline.segments.common.time.date
      # name: time
      # args:
        # format: '%H:%M'
        # istime: true
    - function: powerline.segments.tmux.attached_clients
      priority: 30
      args:
        minimum: 1
    - function: powerline.segments.common.net.hostname
      priority: 10
